# Generated by Django 5.2.4 on 2025-07-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaktorEmisiListrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(help_text='Nama Provinsi atau Jaringan Listrik', max_length=100, unique=True)),
                ('faktor', models.FloatField(help_text='Faktor emisi dalam kg CO2e per kWh')),
            ],
            options={
                'verbose_name': 'Faktor Emisi Listrik',
                'verbose_name_plural': 'Faktor Emisi Listrik',
            },
        ),
        migrations.CreateModel(
            name='FaktorEmisiMakanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_makanan', models.CharField(max_length=100, unique=True)),
                ('faktor', models.FloatField(help_text='Faktor emisi dalam kg CO2e per porsi/kg')),
            ],
            options={
                'verbose_name': 'Faktor Emisi Makanan',
                'verbose_name_plural': 'Faktor Emisi Makanan',
            },
        ),
        migrations.CreateModel(
            name='FaktorEmisiTransportasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kendaraan', models.CharField(max_length=100, unique=True)),
                ('faktor', models.FloatField(help_text='Faktor emisi dalam kg CO2e per km')),
            ],
            options={
                'verbose_name': 'Faktor Emisi Transportasi',
                'verbose_name_plural': 'Faktor Emisi Transportasi',
            },
        ),
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['id'], 'verbose_name': 'Aksi Nyata', 'verbose_name_plural': 'Daftar Aksi Nyata'},
        ),
        migrations.AlterModelOptions(
            name='ecopoint',
            options={'ordering': ['id'], 'verbose_name': 'Titik Lestari', 'verbose_name_plural': 'Daftar Titik Lestari'},
        ),
    ]
