# Generated by Django 5.2.3 on 2025-07-17 20:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_faktoremisilistrik_faktoremisimakanan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='category',
            field=models.CharField(choices=[('Listrik', 'Listrik'), ('Transportasi', 'Transportasi'), ('Konsumsi', 'Konsumsi'), ('Umum', 'Umum')], default='Umum', max_length=20),
        ),
        migrations.AddField(
            model_name='action',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Konten detail seperti langkah-langkah, penjelasan mendalam, dll.', null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='effort_level',
            field=models.CharField(choices=[('Mudah', 'Mudah'), ('Sedang', 'Sedang'), ('Sulit', 'Sulit')], default='Sedang', max_length=10),
        ),
        migrations.AddField(
            model_name='action',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL gambar yang relevan dengan aksi ini.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='impact_level',
            field=models.CharField(choices=[('Tinggi', 'Tinggi'), ('Sedang', 'Sedang'), ('Rendah', 'Rendah')], default='Sedang', max_length=10),
        ),
        migrations.AddField(
            model_name='action',
            name='related_links',
            field=models.TextField(blank=True, help_text='Satu URL per baris untuk sumber atau bacaan lebih lanjut.', null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(help_text='Deskripsi singkat yang muncul di kartu.'),
        ),
    ]
