# Generated by Django 5.2.3 on 2025-07-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_action_category_action_content_action_effort_level_and_more'),
    ]

    operations = [
    ]
