# Generated by Django 5.2.4 on 2025-07-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seed_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='image_url',
        ),
        migrations.AddField(
            model_name='action',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload gambar yang relevan dengan aksi ini.', null=True, upload_to='aksi/'),
        ),
    ]
