# Generated by Django 5.2.4 on 2025-07-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_challenges',
            field=models.JSONField(default=list),
        ),
    ]
