# Generated by Django 5.2.4 on 2025-07-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_completed_challenges'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaktorEmisiBahanBakar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_bahan_bakar', models.CharField(max_length=100, unique=100)),
                ('faktor', models.FloatField(help_text='Faktor emisi dalam kg CO2e per liter')),
            ],
            options={
                'verbose_name': 'Faktor Emisi Bahan Bakar',
                'verbose_name_plural': 'Faktor Emisi Bahan Bakar',
            },
        ),
    ]
