# Generated by Django 5.2.4 on 2025-07-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_action_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faktoremisibahanbakar',
            name='jenis_bahan_bakar',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
