# Generated by Django 5.2.4 on 2025-07-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='points',
            field=models.PositiveIntegerField(default=10, help_text='Poin yang didapat setelah menyelesaikan aksi ini'),
        ),
    ]
