# Generated by Django 5.2.4 on 2025-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_action_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('ONCE', 'Satu Kali'), ('INPUT', 'Berbasis Input')], default='ONCE', help_text='Pilih jenis aksi.', max_length=5),
        ),
        migrations.AddField(
            model_name='action',
            name='points_per_unit',
            field=models.FloatField(default=1.0, help_text='Untuk aksi BERBASIS INPUT, ini adalah poin per satuan.'),
        ),
        migrations.AddField(
            model_name='action',
            name='unit_name',
            field=models.CharField(blank=True, help_text="Satuan untuk aksi berbasis input (misal: 'km', 'kg', 'botol').", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='points',
            field=models.PositiveIntegerField(default=10, help_text='Untuk aksi SATU KALI, ini adalah total poin.'),
        ),
    ]
