# Generated by Django 5.2.4 on 2025-07-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_action_action_type_action_points_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='action',
            name='points',
        ),
        migrations.AlterField(
            model_name='action',
            name='category',
            field=models.CharField(choices=[('Listrik', 'Listrik'), ('Transportasi', 'Transportasi'), ('Konsumsi', 'Konsumsi'), ('Daur Ulang', 'Daur Ulang'), ('Umum', 'Umum')], default='Umum', max_length=20),
        ),
        migrations.AlterField(
            model_name='action',
            name='points_per_unit',
            field=models.FloatField(default=1.0, help_text='Poin yang didapat per satuan.'),
        ),
        migrations.AlterField(
            model_name='action',
            name='unit_name',
            field=models.CharField(default='satuan', help_text="Satuan untuk aksi ini (misal: 'km', 'kg', 'botol').", max_length=20),
            preserve_default=False,
        ),
    ]
