# Generated by Django 5.2.4 on 2025-07-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_id',
            field=models.CharField(help_text='ID unik untuk tantangan, cth: wc01', max_length=20, unique=True, null=True), # Tambahkan null=True
        ),
        migrations.AddField(
            model_name='action',
            name='points',
            field=models.IntegerField(default=10, help_text='Poin yang didapat dari menyelesaikan aksi ini.'),
        ),
    ]
