# Generated by Django 5.2.4 on 2025-07-31 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_action_action_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_image', models.ImageField(upload_to='proofs/')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.action')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'action')},
            },
        ),
    ]
